<?xml version="1.0" encoding="UTF-8"?>
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" expand-text="yes">
   <xsl:strip-space elements="*"/>
   <xsl:template match="/">
      <test-set xmlns="http://www.w3.org/2010/09/qt-fots-catalog" name="misc-ConstructorKeywords">
         <description>
            Tests for constructor functions using keyword arguments.
            Generated by prod/CastExpr/makeKeywordConstructorTests.xsl.
         </description>
         <dependency type="spec" value="XP40+ XQ40+"/>
         <xsl:apply-templates/>
         <test-case name="constructor-keywords-901">
            <description>Wrong keyword error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>xs:nonPositiveInteger(eulav := '0')</test>
            <result>
               <error code="XPST0017"/>
            </result>
         </test-case>
         <test-case name="constructor-keywords-902">
            <description>Wrong arity error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>xs:nonPositiveInteger('0', value := '2')</test>
            <result>
               <error code="XPST0017"/>
            </result>
         </test-case>
         <test-case name="constructor-keywords-903">
            <description>Invalid value error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>xs:positiveInteger(value := '-2')</test>
            <result>
               <error code="FORG0001"/>
            </result>
         </test-case>
         <test-case name="constructor-keywords-904">
            <description>Invalid type error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>xs:nonPositiveInteger(value := current-date())</test>
            <result>
               <error code="XPTY0004"/>
            </result>
         </test-case>
      </test-set>
   </xsl:template>
   <xsl:template match="data/type">
      <test-case xmlns="http://www.w3.org/2010/09/qt-fots-catalog" name="constructor-keywords-{position()}">
         <description>Generated test case</description>
         <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
         <test>{@name}(value := {@value})</test>
         <result>
            <assert-type>{@name}</assert-type>
         </result>
      </test-case>
   </xsl:template>
</xsl:transform>