<?xml version="1.0" encoding="UTF-8"?>
<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" expand-text="yes">
   <xsl:strip-space elements="*"/>
   <xsl:template match="/">
      <test-set xmlns="http://www.w3.org/2010/09/qt-fots-catalog" name="misc-FocusConstructors">
         <description>
            Tests for constructor functions using context item as implicit argument.
            Generated by prod/CastExpr/makeFocusConstructorTests.xsl.
         </description>
         <dependency type="spec" value="XP40+ XQ40+"/>
         <xsl:apply-templates/>
         <test-case name="focus-constructor-901">
            <description>No context item error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test xsl:expand-text="no">let $f := function(){xs:nonPositiveInteger()} return $f()</test>
            <result>
               <error code="XPDY0002"/>
            </result>
         </test-case>
         <test-case name="focus-constructor-902">
            <description>Context item not atomizable error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test xsl:expand-text="no">map{} ! xs:nonPositiveInteger()</test>
            <result>
               <error code="FOTY0013"/>
            </result>
         </test-case>
         <test-case name="focus-constructor-903">
            <description>Invalid value error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>(-2) ! xs:positiveInteger()</test>
            <result>
               <error code="FORG0001"/>
            </result>
         </test-case>
         <test-case name="focus-constructor-904">
            <description>Invalid type error</description>
            <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
            <test>current-date() ! xs:nonPositiveInteger()</test>
            <result>
               <error code="XPTY0004"/>
            </result>
         </test-case>
      </test-set>
   </xsl:template>
   <xsl:template match="data/type">
      <test-case xmlns="http://www.w3.org/2010/09/qt-fots-catalog" name="focus-constructor-{position()}">
         <description>Generated test case</description>
         <created by="Michael Kay" on="{adjust-date-to-timezone(current-date(), ())}"/>
         <test>{@value} ! {@name}()</test>
         <result>
            <assert-type>{@name}</assert-type>
         </result>
      </test-case>
   </xsl:template>
</xsl:transform>